local ADDON, NS = ...
local L = LibStub("AceLocale-3.0"):NewLocale("HomeDecor", "esMX")
if not L then return end

L["ADDON_NAME"]                        = "HomeDecor"
L["SETTINGS"]                          = "Configuración"
L["COMMUNITY"]                         = "Comunidad"
L["WHATS_NEW"]                         = "Novedades"
L["SEARCH_PLACEHOLDER"]                = "Buscar..."
L["LINK"]                              = "Enlace"
L["RESET"]                             = "Restablecer"
L["RESET_ALL_FILTERS"]                 = "Restablecer todos los filtros"
L["FILTERS"]                           = "Filtros"
L["SAVED_ITEMS"]                       = "Objetos guardados"
L["EVENTS"]                            = "Eventos"
L["TRACKERS"]                          = "Rastreadores"
L["DECOR_TRACKER"]                     = "Rastreador de decoración"
L["LUMBER_TRACKER"]                    = "Rastreador de recolección"
L["TRACKER"]                           = "Rastreador"
L["SCALE"]                             = "Escala"
L["SIZE"]                              = "Tamaño"
L["TRANSPARENCY"]                      = "Transparencia"
L["TRANSPARENCY_COLON"]                = "Transparencia:"
L["PANEL_TRANSPARENCY"]                = "Transparencia del panel"
L["WAYPOINT"]                          = "Punto de ruta"
L["SUPPORT_DISCORD"]                   = "Discord de soporte:"
L["AUTO_OPEN"]                         = "Abrir automáticamente"

L["NO_ITEMS_FOUND"]                    = "No se encontraron objetos"
L["NO_VENDORS"]                        = "No hay vendedores"
L["NO_ACTIVE_EVENTS"]                  = "No hay eventos activos"
L["ALL_COLLECTED"]                     = "Todo coleccionado"
L["COLLECTED"]                         = "Coleccionado"

L["VENDOR"]                            = "Vendedor"
L["VENDORS"]                           = "Vendedores"
L["VENDOR_SUFFIX"]                     = " vendedores"
L["VENDOR_OPTIONS"]                    = "Opciones del vendedor"
L["REPUTATION"]                        = "Reputación"
L["CURRENCY"]                          = "Moneda"
L["QUESTS_ACHS"]                       = "Misiones / logros"
L["FACTION"]                           = "Facción"
L["ZONE"]                              = "Zona"
L["DROPS_FROM"]                        = "Lo suelta:"
L["TAG_ACHIEVEMENT"]                   = "[Logro]"
L["TAG_DROP"]                          = "[Botín]"
L["TAG_PROFESSION"]                    = "[Profesión]"
L["TAG_PVP"]                           = "[JcJ]"
L["TAG_QUEST"]                         = "[Misión]"
L["TAG_VENDOR_ITEM"]                   = "[Objeto de vendedor]"
L["DYEABLE"]                           = "Se puede teñir"
L["REQUIRES"]                          = "Requiere"
L["CLASS_HALL"]                        = "Sede de clase"
L["VENDOR_TRACKER"]                    = "Rastreador de vendedores"
L["ALL"]                               = "Todo"
L["ACHIEVEMENTS"]                      = "Logros"
L["DROPS"]                             = "Botines"
L["PROFESSIONS"]                       = "Profesiones"
L["PVP"]                               = "JcJ"
L["QUESTS"]                            = "Misiones"
L["UNCATEGORIZED"]                     = "Sin categoría"
L["CATEGORY"]                          = "Categoría"
L["SUBCATEGORY"]                       = "Subcategoría"
L["EXPANSION"]                         = "Expansión"
L["ALL_CATEGORIES"]                    = "Todas las categorías"
L["ALL_SUBCATEGORIES"]                 = "Todas las subcategorías"
L["ALL_EXPANSIONS"]                    = "Todas las expansiones"
L["ALL_ZONES"]                         = "Todas las zonas"
L["ALL_FACTIONS"]                      = "Todas las facciones"
L["COMPLETED"]                         = "Completado"

L["ITEM_PREFIX"]                       = "Objeto "
L["DECOR_PREFIX"]                      = "Decoración "
L["VENDOR_PREFIX"]                     = "Vendedor "
L["QUEST_PREFIX"]                      = "Misión "
L["ACHIEVEMENT_PREFIX"]                = "Logro "

L["HINT_VIEW_ITEM"]                    = "Clic izquierdo: ver objeto"
L["HINT_EXPAND_COLLAPSE"]              = "Clic izquierdo: expandir/contraer"
L["HINT_VENDOR_LOCATION"]              = "Clic derecho: ubicación del vendedor"
L["HINT_CLICK_WOWHEAD"]                = "Clic: enlace de Wowhead"
L["HINT_ALT_WOWHEAD"]                  = "Alt + clic: enlace de Wowhead"
L["HINT_CTRL_ACHIEVEMENT"]             = "Ctrl + clic: ver logro"
L["HINT_SHIFT_MISSING"]                = "Mantén presionada la tecla Mayús: mostrar faltantes"
L["HINT_CLICK_MAP"]                    = "Clic: abrir mapa"
L["HINT_CTRL_COPY"]                    = "Ctrl+C para copiar y luego pegar en tu navegador."
L["HINT_CTRL_WOWHEAD"]                 = "Usa Ctrl + clic para abrir el enlace correcto de Wowhead."
L["TREASURE_HUNT_WARNING"]             = "Existen muchas versiones de la misión Búsqueda del tesoro de decoración."

L["REQ_REPUTATION"]                    = "Reputación requerida"
L["REQ_QUEST"]                         = "Misión requerida"
L["REQ_NONE_QUEST_ACH"]                = "No se requiere ninguna misión ni logro"
L["REQ_NONE_REPUTATION"]               = "No se requiere reputación"
L["WOWHEAD_LINKS"]                     = "Enlaces de Wowhead"

L["OPT_SUBTITLE"]                      = "Opciones de calidad de vida para el addon."
L["OPT_SHOW_MINIMAP_BTN"]              = "Mostrar botón del minimapa"
L["OPT_MINIMAP"]                       = "Minimapa"
L["OPT_MINIMAP_PINS"]                  = "Mostrar marcadores de vendedores en el minimapa"
L["OPT_SHOW_DISTANT_PINS"]             = "Mostrar marcadores de vendedores fuera del alcance del minimapa"
L["OPT_SHOW_DISTANT_PINS_TIP"]         = "Cuando está activado, los vendedores que estén demasiado lejos para aparecer en el minimapa se mostrarán en el borde. Cuando está desactivado, permanecerán ocultos hasta que te acerques."
L["OPT_WORLD_MAP"]                     = "Mapa del mundo"
L["OPT_WORLDMAP_PINS"]                 = "Mostrar marcadores de vendedores en el mapa del mundo"
L["OPT_HIDE_COLLECTED"]                = "Ocultar objetos ya coleccionados"
L["OPT_HIDE_COLLECTED_TIP"]            = "Oculta los objetos que ya has coleccionado del navegador y de las vistas de lista"
L["OPT_PIN_APPEARANCE"]                = "Apariencia de los marcadores"
L["OPT_PIN_STYLE"]                     = "Estilo del marcador:"
L["OPT_PIN_HOUSE"]                     = "Ícono de casa"
L["OPT_PIN_DOT"]                       = "Punto"
L["OPT_PIN_COLOR"]                     = "Color del marcador"
L["OPT_RESET_COLOR"]                   = "Restablecer color"
L["OPT_PIN_SIZE"]                      = "Tamaño del marcador"
L["OPT_TRACKER_HEADER"]                = "Rastreador"
L["OPT_HIGHLIGHT_ZONE"]                = "Resaltar objetos guardados al entrar en una zona"
L["OPT_HIGHLIGHT_ZONE_TIP"]            = "Cuando está activado, los objetos guardados se resaltarán al entrar en una nueva zona"

L["OPT_BROWSER_HEADER"]                = "Navegador"
L["OPT_COMPACT_MODE"]                  = "Abrir en modo compacto"
L["OPT_COMPACT_MODE_TIP"]              = "Cuando está activado, el botón del minimapa y el comando de barra abrirán la vista de lista compacta en lugar del navegador completo"

L["OPT_VENDOR_SUBTITLE"]               = "Controla la información que HomeDecor muestra sobre la ventana del vendedor."
L["OPT_SHOW_CHECKMARK"]                = "Mostrar marca de objetos coleccionados"
L["OPT_SHOW_CHECKMARK_TIP"]            = "Muestra una marca en los objetos del vendedor que ya posees en tu almacén de vivienda"
L["OPT_SHOW_OWNED_COUNT"]              = "Mostrar cantidad en posesión"
L["OPT_SHOW_OWNED_COUNT_TIP"]          = "Muestra un número en los objetos del vendedor indicando cuántos tienes en tu almacén de vivienda"
L["OPT_VENDOR_TOOLTIP"]                = "Mostrar información de HomeDecor en el tooltip del vendedor"
L["OPT_VENDOR_TOOLTIP_TIP"]            = "Muestra información de HomeDecor en el tooltip al pasar el cursor sobre un PNJ vendedor"
L["VENDOR_ASSISTANT"]                  = "Asistente del vendedor"
L["VENDOR_ASSISTANT_MISSING"]          = "Faltantes"
L["VENDOR_ASSISTANT_SAVED"]            = "Guardados"
L["VENDOR_ASSISTANT_NO_ITEMS"]         = "Ningún objeto de decoración coincide con este filtro."
L["VENDOR_ASSISTANT_TOGGLE"]           = "Abrir panel del vendedor de HomeDecor"
L["VENDOR_ASSISTANT_TOTAL"]            = "Total de compra:"
L["VENDOR_ASSISTANT_SAVED_HINT"]       = "Haz clic para agregar o quitar de Objetos guardados."
L["VENDOR_ASSISTANT_SUBTITLE"]         = "Lista de compras de decoración"
L["VENDOR_ASSISTANT_EMPTY_MISSING"]    = "No te falta nada de este vendedor."
L["VENDOR_ASSISTANT_EMPTY_SAVED"]      = "Marca con una estrella la decoración faltante para guardarla aquí."
L["VENDOR_ASSISTANT_OPTIONS"]          = "Opciones del panel"
L["VENDOR_ASSISTANT_COMPACT_ROWS"]     = "Filas de objetos compactas"
L["VENDOR_ASSISTANT_SHOW_PRICES"]      = "Mostrar precios"

L["MAP_TRACKER_SETTINGS"]              = "Configuración del mapa y del rastreador"
L["MAP_PINS_HEADER"]                   = "Marcadores del mapa"
L["MAP_SHOW_MINIMAP"]                  = "Mostrar en el minimapa"
L["MAP_SHOW_WORLDMAP"]                 = "Mostrar en el mapa del mundo"
L["MAP_HIDE_COLLECTED"]                = "Ocultar objetos coleccionados"
L["MAP_HIDE_COMPLETED_VENDORS"]        = "Ocultar vendedores completados"
L["MAP_PIN_STYLE_HEADER"]              = "Apariencia de los marcadores"
L["MAP_STYLE"]                         = "Estilo"
L["MAP_COLOR"]                         = "Color"
L["MAP_SIZE"]                          = "Tamaño"

L["TRACK_CURRENT_ZONE"]                = "Rastrear zona actual"
L["HIDE_COMPLETED"]                    = "Ocultar completados:"
L["HIGHLIGHT_SAVED"]                   = "Resaltar objetos guardados:"

L["FILTER_HIDE_COMPLETED"]             = "Ocultar completados"
L["FILTER_ALTS_REP_HINT"]              = "Inicia sesión con tus alters una vez para actualizar las reputaciones que has completado"
L["FILTER_ALTS_QUEST_HINT"]            = "Inicia sesión con tus alters una vez para actualizar las misiones que has completado con cualquier personaje"
L["FILTER_ACH_COMPLETED_HINT"]         = "Mostrar solo objetos de los logros que has completado"

L["LUMBER_TOTAL"]                      = "Total de madera: "
L["LUMBER_TOTAL_ZERO"]                 = "Total de madera: 0"
L["LUMBER_GOAL_AMOUNT"]                = "Cantidad objetivo:"
L["LUMBER_HIGHLIGHT_SAVED"]            = "Resaltar objetos guardados:"
L["LUMBER_COMPACT_MODE"]               = "Modo compacto"
L["LUMBER_COMPACT_TIP"]                = "Muestra una lista condensada en una sola línea; permite mostrar más objetos ocupando menos espacio en pantalla"
L["LUMBER_TOGGLE_COMPACT"]             = "Alternar vista compacta de una sola línea"
L["LUMBER_SHOW_ICONS"]                 = "Mostrar íconos"
L["LUMBER_HIDE_ZERO"]                  = "Ocultar objetos con 0"
L["LUMBER_TRACK_LUMBER"]               = "Rastrear madera"
L["LUMBER_TRACK_LUMBER_TIP"]           = "Muestra la madera en el rastreador."
L["LUMBER_TRACK_ORE"]                  = "Rastrear mineral"
L["LUMBER_TRACK_ORE_TIP"]              = "Muestra el mineral y la piedra de minería en el rastreador."
L["LUMBER_TRACK_HERBS"]                = "Rastrear hierbas"
L["LUMBER_TRACK_HERBS_TIP"]            = "Muestra las hierbas en el rastreador."
L["LUMBER_ACCOUNT_WIDE"]               = "Para toda la cuenta"
L["LUMBER_ACCOUNT_WIDE_TIP"]           = "Combina las cantidades de madera de todos los personajes.\n\nPasa el cursor sobre las filas para ver el desglose por personaje."
L["LUMBER_AUTO_CALC_GOALS"]            = "Calcular objetivos automáticamente"
L["LUMBER_AUTO_CALC_GOALS_TIP"]        = "Calcula automáticamente los objetivos según las recetas de decoración de vivienda que aún no has fabricado"
L["LUMBER_AUTO_FARM"]                  = "Modo de farmeo automático"
L["LUMBER_AUTO_FARM_TIP"]              = "Comienza automáticamente a registrar las estadísticas de farmeo cuando saquees madera"
L["LUMBER_HIDE_IN_INSTANCE"]           = "Ocultar en instancias"
L["LUMBER_HIDE_IN_INSTANCE_TIP"]       = "Oculta automáticamente las ventanas del Rastreador de madera y Estadísticas de farmeo al entrar en una mazmorra, banda o instancia JcJ"
L["LUMBER_FARMING_SETTINGS"]           = "Configuración de farmeo"
L["LUMBER_FARMING_STATS"]              = "Estadísticas de farmeo"
L["LUMBER_CHARACTER_BREAKDOWN"]        = "Desglose por personaje:"
L["LUMBER_WARBAND_BANK"]               = "Banco de la banda guerrera"
L["LUMBER_BTN_START_FARMING"]          = "INICIAR FARMEO"
L["LUMBER_BTN_START"]                  = "INICIAR"
L["LUMBER_BTN_PAUSE"]                  = "PAUSAR"
L["LUMBER_BTN_RESUME"]                 = "REANUDAR"
L["LUMBER_BTN_RESET"]                  = "RESTABLECER"
L["LUMBER_STAT_SESSION"]               = "SESIÓN"
L["LUMBER_STAT_TOTAL"]                 = "TOTAL"
L["LUMBER_STAT_BAGS"]                  = "BOLSAS"
L["LUMBER_STAT_COLLECTING"]            = "RECOLECTANDO"

L["LDB_LEFT_CLICK"]                   = "Clic izquierdo: abrir"
L["LDB_RIGHT_CLICK"]                  = "Clic derecho: opciones"
L["LDB_TOGGLE_TIP"]                   = "Haz clic para mostrar u ocultar HomeDecor"

L["SLASH_HEADER"]                     = "Comandos de HomeDecor:"
L["SLASH_HD"]                         = "/hd                 - Mostrar u ocultar HomeDecor"
L["SLASH_MINIMAP"]                    = "/hd minimap [show|hide]"
L["SLASH_PINS"]                       = "/hd pins [minimap|worldmap]  - Mostrar u ocultar marcadores de vendedores"
L["SLASH_OPTIONS"]                    = "/hd options          - Abrir opciones"
L["SLASH_CHANGELOG"]                  = "/hd changelog       - Mostrar novedades"

L["JOIN_DISCORD"]                     = "Únete a nuestra comunidad de Discord"
L["SUPPORT_BUYMEACOFFEE"]             = "Apoya el desarrollo (Buy Me a Coffee)"
L["DONATE_PAYPAL"]                    = "Donar mediante PayPal"
L["SHARE_HOMEDECOR"]                  = "Comparte HomeDecor con tus amigos"

L["ITEM_LINK"]                        = "Enlace del objeto"
L["QUEST_LINK"]                       = "Enlace de la misión"
L["ACHIEVEMENT_LINK"]                 = "Enlace del logro"

L["VIEW_ICON"]                        = "Ícono"
L["VIEW_LIST"]                        = "Lista"

L["DYEABLE_CLASS"]                    = "Se puede teñir - "

L["GOAL_MANUAL_PREFIX"]               = "Objetivo manual: "
L["GOAL_MANUAL_SUB"]                  = "(Se configura en las opciones)"
L["GOAL_AUTO_PREFIX"]                 = "Objetivo automático: "
L["GOAL_AUTO_SUB"]                    = "Basado en las recetas de decoración de vivienda que aún no has fabricado"
L["GOAL_AUTO_COMPLETE"]               = "Toda la decoración de vivienda conocida que usa esta madera está completa"

L["EVENT_ITEMS_PLACEHOLDER"]          = "Los objetos del evento aparecerán aquí mientras esté activo"

L["UNKNOWN"]                          = "Desconocido"

L["EXP_CLASSIC"]                      = "Classic"
L["EXP_TBC"]                          = "Burning Crusade"
L["EXP_WOTLK"]                        = "Wrath of the Lich King"
L["EXP_MOP"]                          = "Mists of Pandaria"
L["EXP_WOD"]                          = "Warlords of Draenor"
L["EXP_LEGION"]                       = "Legion"
L["EXP_BFA"]                          = "Battle for Azeroth"
L["EXP_SHADOWLANDS"]                  = "Shadowlands"
L["EXP_DRAGONFLIGHT"]                 = "Dragonflight"
L["EXP_TWW"]                          = "The War Within"

L["ZONE_EASTERN_KINGDOMS"]            = "Reinos del Este"
L["ZONE_KALIMDOR"]                    = "Kalimdor"
L["ZONE_OUTLAND"]                     = "Terrallende"
L["ZONE_NORTHREND"]                   = "Rasganorte"
L["ZONE_THE_MAELSTROM"]               = "La Vorágine"
L["ZONE_PANDARIA"]                    = "Pandaria"
L["ZONE_DRAENOR"]                     = "Draenor"
L["ZONE_BROKEN_ISLES"]                = "Islas Quebradas"
L["ZONE_ARGUS"]                       = "Argus"
L["ZONE_ZANDALAR"]                    = "Zandalar"
L["ZONE_KUL_TIRAS"]                   = "Kul Tiras"
L["ZONE_DRAGON_ISLES"]                = "Islas Dragón"
L["ZONE_KHAZ_ALGAR"]                  = "Khaz Algar"
L["ZONE_FOUNDERS_POINT"]              = "Punta del Fundador"
L["ZONE_RAZORSHORE"]                  = "Costa Filo"

L["ERR_MAPOPUP_FAILED"]               = "HomeDecor: no se pudo crear el marco MapPopup"
L["ERR_MAPOPUPUI_UNAVAILABLE"]        = "HomeDecor: MapPopupUI no está disponible"

L["MORE_ITEMS"]                       = "más..."

L["DECOR_PRICING"]                    = "Precios de decoración"
L["DECOR_AH_CRAFTING_QUEUE"]          = "Cola de fabricación"
L["DECOR_AH_CLEAR"]                   = "Limpiar"
L["DECOR_AH_CLEAR_ALL"]               = "Limpiar todo"
L["DECOR_AH_MATERIALS_SUMMARY"]       = "Resumen de materiales"
L["DECOR_AH_TOTAL_MATERIALS"]         = "Materiales totales:"
L["DECOR_AH_PROFIT_COLON"]            = "Ganancia:"
L["DECOR_AH_COST_COLON"]              = "Costo:"
L["DECOR_AH_EXPORT_LIST"]             = "Exportar lista"
L["DECOR_AH_EXPORT"]                  = "Exportar"
L["DECOR_AH_IMPORT"]                  = "Importar"
L["DECOR_AH_AUCTIONATOR"]             = "Auctionator"
L["DECOR_AH_REMOVE"]                  = "Quitar"
L["DECOR_AH_UNKNOWN_ITEM"]            = "Objeto desconocido"
L["DECOR_AH_PROFIT_PREFIX"]           = "Ganancia: "
L["DECOR_AH_LOSS_PREFIX"]             = "Pérdida: "
L["DECOR_AH_PROFIT_UNKNOWN"]          = "Ganancia: desconocida"
L["DECOR_AH_EXPORT_SHOPPING_LIST"]    = "Exportar lista de compras"
L["DECOR_AH_COPY_ALL"]                = "Copiar todo"
L["DECOR_AH_SALES_TRACKER"]           = "Rastreador de ventas"
L["DECOR_AH_SALES"]                   = "Ventas"
L["DECOR_AH_TODAY"]                   = "Hoy"
L["DECOR_AH_THIS_WEEK"]               = "Esta semana"
L["DECOR_AH_SUMMARY_COLON"]           = "Resumen:"
L["DECOR_AH_REFRESH"]                 = "Actualizar"
L["DECOR_AH_CLEAR_DATA"]              = "Borrar datos"
L["DECOR_AH_TOTAL_REVENUE"]           = "Ingresos totales: "
L["DECOR_AH_EST_PROFIT"]              = "Ganancia estimada: "
L["DECOR_AH_EST_PROFIT_NA"]           = "Ganancia estimada: no disponible"
L["DECOR_AH_MATERIALS_COLON"]         = "Materiales:"
L["DECOR_AH_CLICK_STAR"]              = "Haz clic en la estrella para marcar como favorito"
L["DECOR_AH_RIGHTCLICK_QUEUE"]        = "Clic derecho para agregar a la cola"
L["DECOR_AH_USE_PRICES_FROM"]         = "Usar precios de:"
L["DECOR_AH_LAST_SCAN"]               = "Último escaneo de Auctionator"
L["DECOR_AH_CLICK_MARK_SCANNED"]      = "Haz clic para marcar que acabas de escanear con Auctionator."
L["DECOR_AH_OPENS_AH"]                = "Abre la Casa de Subastas para realizar un escaneo completo."
L["DECOR_AH_INSTALL_TIP"]             = "Instala Auctionator para escanear precios automáticamente."
L["DECOR_AH_INSTALL_AUCTIONATOR"]     = "Instalar Auctionator"
L["DECOR_AH_RUN_FULL_SCAN"]           = "Realizar escaneo completo"
L["DECOR_AH_QUEUE_ZERO"]              = "Cola (0)"
L["DECOR_AH_QUEUE_TIP"]               = "Cola de fabricación"
L["DECOR_AH_RIGHTCLICK_ADD_QUEUE"]    = "Haz clic derecho en los objetos para agregarlos a la cola"
L["DECOR_AH_VIEW_MATERIALS"]          = "Ver materiales y exportar lista de compras"
L["DECOR_AH_VIEW_SOLD"]               = "Ver tus subastas vendidas y ganancias"
L["DECOR_AH_TRACKS_MAIL"]             = "Registra los objetos vendidos mediante el correo"
L["DECOR_AH_PROFESSION_COLON"]        = "Profesión:"
L["DECOR_AH_EXPANSION_COLON"]         = "Expansión:"
L["DECOR_AH_LUMBER_COLON"]            = "Madera:"
L["DECOR_AH_SEARCH_COLON"]            = "Buscar:"
L["DECOR_AH_SCALE"]                   = "Escala"
L["DECOR_AH_CREATE_AUCTIONATOR"]      = "Crear lista de compras de Auctionator"
L["DECOR_AH_CREATES_SHOPPING_LIST"]   = "Crea la lista de compras 'HomeDecor' con todos los materiales comerciables de la cola."
L["DECOR_AH_QUEUE_EMPTY"]             = "La cola está vacía"
L["DECOR_AH_QUEUE_EMPTY_HINT"]        = "Agrega objetos desde la pestaña Visor para comenzar a crear tu cola de fabricación"
L["DECOR_AH_EXPORT_FORMAT_COLON"]     = "Formato de exportación:"
L["DECOR_AH_CLOSE"]                   = "Cerrar"
L["DECOR_AH_IMPORT_TITLE"]            = "Importar lista de compras"
L["DECOR_AH_PASTE_LIST"]              = "Pega la lista de compras de TSM/Auctionator:"
L["DECOR_AH_CANCEL"]                  = "Cancelar"

L["DECOR_AH_JUST_SCANNED"]             = "Recién escaneado"
L["DECOR_AH_SCANNED_MIN_AGO"]          = "Escaneado hace %dm"
L["DECOR_AH_SCANNED_HOURS_AGO"]        = "Escaneado hace %dh"
L["DECOR_AH_QUEUE_COUNT"]              = "Cola (%d)"

L["DROPS_LABEL"]                       = "Botines"
L["DROPS_FROM_PANEL"]                  = "Lo suelta"

L["MAPPIN_LEFT_CLICK_SET_WP"]          = "Clic izquierdo: establecer punto de ruta"
L["MAPPIN_LEFT_CLICK_CLEAR_WP"]        = "Clic izquierdo: borrar punto de ruta"
L["MAPPIN_RIGHT_CLICK_VENDOR_ITEMS"]    = "Clic derecho: mostrar objetos del vendedor"
L["MAPPIN_NPC_ID"]                     = "ID del PNJ: "
L["MAPPIN_LEFT_CLICK_ZONE_MAP"]        = "Clic izquierdo: ver mapa de la zona"
L["MAPPIN_RIGHT_CLICK_ALL_VENDORS"]    = "Clic derecho: mostrar todos los vendedores"

L["MAP_POPUP_VENDORS"]                 = "Vendedores"

L["ALTS_PROFESSIONS"]                  = "Profesiones de alters"
L["ALTS_CLICK_CELL_HINT"]              = "Haz clic en cualquier celda para ver alters y recetas"
L["ALTS_YOUR_ALTS"]                    = "TUS ALTERS"
L["ALTS_PROFITABLE_RECIPES"]           = "RECETAS RENTABLES"
L["ALTS_TRAINER_LOCATIONS"]            = "UBICACIONES DE LOS INSTRUCTORES"
L["ALTS_SECTION_LABEL"]                = "Profesiones de alters"
L["ALTS_NOT_LEARNED"]                  = "No aprendida en ningún alter"
L["ALTS_NO_ITEMS_MATCH"]               = "Ningún objeto coincide con el filtro actual"
L["ALTS_NO_RECIPES_YET"]               = "¡Aún no hay recetas de decoración de vivienda aquí!"
L["ALTS_SHOW"]                         = "MOSTRAR:"
L["ALTS_SORT"]                         = "ORDENAR:"
L["ALTS_MKT"]                          = "Merc.:"
L["ALTS_COST"]                         = "Costo:"
L["ALTS_FIND_TRAINER"]                 = "Buscar instructor"
L["ALTS_TRAINER_LOCATIONS_TIP"]        = "Ubicaciones de los instructores"

L["TRACKER_TITLE"]                     = "Rastreador de decoración"

L["LUMBER_FARMING_STATS_TITLE"]        = "Estadísticas de farmeo"

L["FILTER_TAB_FILTERS"]                = "Filtros"
L["FILTER_TAB_COMPLETED"]              = "Completado"
L["FILTER_HIDE_COMPLETED_ROW"]         = "Ocultar completados"
L["FILTER_REPUTATION_ROW"]             = "Reputación"
L["FILTER_QUESTS_ROW"]                 = "Misiones"
L["FILTER_ACHIEVEMENT_ROW"]            = "Logro"

L["FILTER_HIDE_PVP_ROW"]               = "Ocultar objetos JcJ"
L["FILTER_HIDE_PVP_HINT"]              = "Ocultar objetos JcJ de las demás categorías"
L["FILTER_FACTION_ROW"]                = "Facción"
L["FILTER_EXPANSION_ROW"]              = "Expansión"
L["FILTER_ZONE_ROW"]                   = "Zona"
L["FILTER_CATEGORY_ROW"]               = "Categoría"
L["FILTER_SUBCATEGORY_ROW"]            = "Subcategoría"
L["FILTER_ALLIANCE"]                   = "Alianza"
L["FILTER_HORDE"]                      = "Horda"

L["MAP_PANEL_MAP_PINS"]                = "Marcadores del mapa"
L["MAP_PANEL_VENDOR_TRACKER"]          = "Rastreador de vendedores"
L["MAP_PANEL_PIN_APPEARANCE"]          = "Apariencia de los marcadores"
L["MAP_PANEL_SHOW_WORLDMAP"]           = "Mostrar en el mapa del mundo"
L["MAP_PANEL_SHOW_MINIMAP"]            = "Mostrar en el minimapa"
L["MAP_PANEL_HIDE_COLLECTED"]          = "Ocultar objetos coleccionados"
L["MAP_PANEL_HIDE_COMPLETED_VEND"]     = "Ocultar vendedores completados"
L["MAP_PANEL_STYLE"]                   = "Estilo"
L["MAP_PANEL_COLOR"]                   = "Color"
L["MAP_PANEL_TOOLTIP_ANCHOR_SECTION"]    = "Posición del tooltip"
L["MAP_PANEL_TOOLTIP_ANCHOR"]            = "Anclaje"

L["LUMBER_SHOW_ICONS_TIP"]             = ""
L["LUMBER_COMPACT_MODE_TIP"]           = "Muestra una lista condensada en una sola línea; permite mostrar más objetos ocupando menos espacio en pantalla"
L["LUMBER_AUTO_FARM_TIP_LONG"]         = "Comienza automáticamente a registrar las estadísticas de farmeo cuando saquees madera"
L["LUMBER_ACCOUNT_WIDE_TIP_LONG"]      = "Combina las cantidades de madera de todos los personajes.\n\nPasa el cursor sobre las filas para ver el desglose por personaje."
L["LUMBER_AUTO_CALC_GOALS_TIP_LONG"]   = "Calcula automáticamente los objetivos según las recetas de decoración de vivienda que aún no has fabricado"

L["CURRENCY_FALLBACK"]                 = "Moneda"
L["DECOR_HASH_PREFIX"]                 = "Decoración #"
L["DYEABLE_LABEL"]                     = "Se puede teñir"
L["DYEABLE_CLASS_LABEL"]               = "Se puede teñir - "
L["NO_ITEMS_MATCH_SEARCH"]             = "Ningún objeto coincide con tu búsqueda"
L["NO_ACTIVE_EVENTS_TITLE"]            = "No hay eventos activos"

L["REQ_REPUTATION_TEXT"]               = "Reputación requerida"
L["REQ_QUEST_TEXT"]                    = "Misión requerida"

L["CLASS_HALL_HEADER"]                 = "Sede de clase"

L["ALTS_FILTER_ALL_ITEMS"]             = "Todos los objetos"
L["ALTS_FILTER_WITH_PRICE"]            = "Con datos de precios"
L["ALTS_FILTER_PROFITABLE"]            = "Solo rentables"
L["ALTS_FILTER_HIGH"]                  = "Alta (>100 g)"
L["ALTS_FILTER_MEGA"]                  = "Muy alta (>300 g)"
L["ALTS_FILTER_CAN_CRAFT"]             = "Puede fabricar"
L["ALTS_SORT_PROFIT_HL"]               = "Ganancia de mayor a menor"
L["ALTS_SORT_PROFIT_LH"]               = "Ganancia de menor a mayor"
L["ALTS_SORT_MARGIN_HL"]               = "Margen de mayor a menor"
L["ALTS_SORT_NAME_AZ"]                 = "Nombre A-Z"
L["ALTS_KNOWN_ONLY"]                   = "Solo conocidas"
L["ALTS_ALT_PROFESSIONS"]              = "Profesiones de alters"
L["ALTS_READY_NOW"]                    = "LISTO AHORA"
L["ALTS_TAB_OPPORTUNITIES"]            = "Oportunidades"
L["ALTS_TAB_ITEM_TRACKER"]             = "Rastreador de objetos"
L["ALTS_LEGEND_READY"]                 = "Listo"
L["ALTS_LEGEND_FAR"]                   = "Lejos"
L["ALTS_LEGEND_NONE"]                  = "Ninguno"

L["EVENTS_ENDS_IN"]                    = "Termina en "

L["DECOR_AH_NO_ITEMS_FOUND"]           = "No se encontraron objetos"
L["DECOR_AH_NO_ITEMS_MATCH"]           = "Ningún objeto coincide con tu búsqueda"
L["DECOR_AH_KNOWN_ONLY"]               = "Solo conocidas"
L["DECOR_AH_ALT_PROFESSIONS"]          = "Profesiones de alters"
L["DECOR_AH_FORMAT_TEXT"]              = "Texto"
L["DECOR_AH_FORMAT_TSM"]               = "TSM"
L["DECOR_AH_FORMAT_AUCTIONATOR"]       = "Auctionator"

L["SALES_CONFIRM_CLEAR"]               = "Limpiar"
L["SALES_CONFIRM_CANCEL"]              = "Cancelar"

L["MAP_POPUP_CLASS_HALL"]              = "Sede de clase"

L["LUMBER_WARBAND_BANK_LABEL"]         = "Banco de la banda guerrera"

L["ALTS_CLOSE_SKL"]                    = "CERCA (<50 HAB.)"
L["ALTS_LEGEND_CLOSE"]                 = "Cerca (<50)"

L["FILTER_ALL"]                        = "Todo"

L["EVENTS_PLACEHOLDER_BODY"]           = "Los objetos del evento aparecerán aquí mientras esté activo"

L["PROF_TIP_TITLE"]                    = "Consejo sobre profesiones"
L["PROF_TIP_MESSAGE"]                  = "Asegúrate de iniciar sesión con todos los alters que tengan profesiones y abrir la ventana de Profesiones para que el addon registre toda la información."
L["PROF_TIP_OK"]                       = "¡Entendido!"

L["CONFLICT_TITLE"]           = "Conflicto de funciones de edición"
L["CONFLICT_LINE1"]           = "Otro addon proporciona funciones de edición que se superponen."
L["CONFLICT_LINE2"]           = "¿Quieres desactivar las funciones de edición de HomeDecor?"
L["CONFLICT_LINE3"]           = "Puedes cambiar esta opción en cualquier momento desde las opciones de HomeDecor."
L["CONFLICT_BTN_DISABLE"]     = "Desactivar HomeDecor"
L["CONFLICT_BTN_KEEP"]        = "Mantener HomeDecor"
L["CONFLICT_BTN_LATER"]       = "Decidir más tarde"
L["CONFLICT_MSG_DISABLED"]    = "Las funciones de edición se desactivaron. Puedes volver a activarlas en cualquier momento desde las opciones."
L["CONFLICT_MSG_KEPT"]        = "Las funciones de edición permanecen activas."
L["CONFLICT_MSG_LATER"]       = "Decide más tarde desde las opciones o con |cffffff00/homedecor conflict|r."
L["CONFLICT_NOT_READY"]       = "Las SavedVariables aún no están listas."
L["CONFLICT_RESET"]           = "Las preferencias de conflicto se restablecieron. Volviendo a analizar..."

L["OPT_EDITOR_PANEL_NAME"]        = "Editor de vivienda"
L["OPT_EDITOR_SUBTITLE"]          = "Configura las funciones y atajos de teclado de HomeDecor para el editor de vivienda."
L["OPT_EDITOR_GENERAL"]           = "General"
L["OPT_EDITOR_ENABLE"]            = "Activar funciones de edición"
L["OPT_EDITOR_ENABLE_TIP"]        = "Interruptor principal. Al desactivarlo, se ocultan todas las superposiciones de HomeDecor dentro del editor."
L["OPT_EDITOR_HUD"]               = "Mostrar panel de ayuda de atajos de teclado"
L["OPT_EDITOR_HUD_TIP"]           = "Muestra el panel lateral derecho con los atajos de teclado activos mientras estás en el editor de vivienda."
L["OPT_EDITOR_CLIPBOARD"]         = "Portapapeles"
L["OPT_EDITOR_CLIPBOARD_CB"]      = "Activar portapapeles"
L["OPT_EDITOR_CLIPBOARD_TIP"]     = "Activa las funciones Copiar, Cortar, Pegar, Duplicar, Colocación en lote, Bloquear/Desbloquear y el panel de rotación."
L["OPT_EDITOR_QUICKBAR"]          = "Barra rápida"
L["OPT_EDITOR_QUICKBAR_CB"]       = "Mostrar barra rápida"
L["OPT_EDITOR_QUICKBAR_TIP"]      = "Muestra la barra rápida numerada de decoración. Solo tiene efecto mientras estás dentro del editor de vivienda."
L["OPT_EDITOR_KEYBINDS"]          = "Atajos de teclado"
L["OPT_EDITOR_KB_NOTE"]           = "Haz clic en un botón y luego presiona una tecla para reasignarla. Presiona Escape para borrar la asignación."
L["OPT_EDITOR_QB_KEYBINDS"]       = "Atajos de teclado de la barra rápida"
L["OPT_EDITOR_SLOT"]              = "Ranura"
L["OPT_EDITOR_PRESS_KEY"]         = "Presiona una tecla\226\128\166"
L["OPT_EDITOR_CONFLICTS"]         = "Conflictos entre addons"
L["OPT_EDITOR_CONFLICTS_NOTE"]    = "Elige qué addon administrará las funciones de edición cuando se detecte un conflicto."
L["OPT_EDITOR_NO_CONFLICTS"]      = "No se detectaron addons en conflicto."
L["OPT_EDITOR_OTHER_ADDON"]       = "Otro addon"
L["OPT_EDITOR_RECENT"]            = "Ranura reciente"
L["OPT_EDITOR_MODEBAR"]           = "Barra de modos"
L["OPT_KB_COPY"]                  = "Copiar"
L["OPT_KB_CUT"]                   = "Cortar"
L["OPT_KB_PASTE"]                 = "Pegar"
L["OPT_KB_DUPLICATE"]             = "Duplicar"
L["OPT_KB_LOCK"]                  = "Bloquear / desbloquear"
L["LUMBER_OPTIONS"]               = "Rastreador de recolección"
L["OPT_LUMBER_SUBTITLE"]          = "Configura el Rastreador de recolección principal y abre rastreadores compactos independientes para materiales."
L["OPT_LUMBER_DISPLAY"]           = "Visualización"
L["OPT_LUMBER_SHOW_ICONS_TIP"]    = "Muestra los íconos de los objetos junto a cada entrada de madera."
L["OPT_LUMBER_HIDE_ZERO_TIP"]     = "Oculta los tipos de madera cuya cantidad sea cero."
L["OPT_LUMBER_GOALS"]             = "Objetivos"
L["OPT_LUMBER_FARMING"]           = "Farmeo"
L["OPT_LUMBER_ACCOUNT"]           = "Cuenta"
L["OPT_LUMBER_ACCOUNT_WIDE_TIP"]  = "Combina las cantidades de madera de todos los personajes. Pasa el cursor sobre las filas para ver el desglose por personaje."
L["OPT_GATHER_MINI_TRACKERS"]     = "Materiales"
L["OPT_GATHER_OPEN_LUMBER"]       = "Abrir madera"
L["OPT_GATHER_OPEN_ORE"]          = "Abrir mineral"
L["OPT_GATHER_OPEN_HERB"]         = "Abrir hierbas"
L["OPT_GATHER_OPEN_ALL"]          = "Abrir todos los materiales"
L["OPT_GATHER_FARM_LUMBER"]       = "Farmear madera"
L["OPT_GATHER_FARM_ORE"]          = "Farmear mineral"
L["OPT_GATHER_FARM_HERB"]         = "Farmear hierbas"
L["OPT_WORLDMAP_TOOLTIP_ANCHOR"]  = "Posición del tooltip del marcador del mapa"
L["ANCHOR_LEFT"]                  = "Izquierda"
L["ANCHOR_RIGHT"]                 = "Derecha"
L["ANCHOR_MIDDLE"]                = "Centro"
L["ANCHOR_BOTTOM"]                = "Abajo"
L["ANCHOR_CURSOR"]                = "Cursor"
