----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "esMX" then
    return
end

local L = BtWQuests.L
L["ALLIED_RACE_MECHAGNOME"] = "Razas aliadas: Mecagnomo"
L["ALLIED_RACE_VULPERA"] = "Razas aliadas: Vulpera"
L["AN_ALLIANCE_FOOTHOLD"] = "Un enclave de la Alianza"
L["ASSAULT_AMATHET_ADVANCE_ACTIVE"] = "Asalto: Avanzada Amathet activo"
L["ASSAULT_AQIR_UNEARTHED_ACTIVE"] = "Asalto: Aqir desenterrados activo"
L["ASSAULT_THE_ENDLESS_SWARM_ACTIVE"] = "Asalto: El enjambre interminable activo"
L["ASSAULT_THE_WARRING_CLANS_ACTIVE"] = "Asalto: Los clanes en guerra activo"
L["A_HORDE_FOOTHOLD"] = "Un enclave de la Horda"
L["BTWQUESTS_ALLIED_RACE_DARK_IRON_DWARF"] = "Raza aliada: Enano Hierro Negro"
L["BTWQUESTS_ALLIED_RACE_KUL_TIRAN"] = "Raza aliada: Kultirano"
L["BTWQUESTS_ALLIED_RACE_MAGHAR_ORC"] = "Raza aliada: Orco Mag'har"
L["BTWQUESTS_ALLIED_RACE_ZANDALARI_TROLL"] = "Raza aliada: Trol Zandalari"
L["BTWQUESTS_BEGIN_THE_BATTLE_FOR_BRENNADAM"] = "Comienza la batalla por Brennadam"
L["BTWQUESTS_COSMETIC_WAIST_OF_TIME"] = "Cosmético: Pérdida de tiempo"
L["BTWQUESTS_FLIGHT_MASTER_KELYA_MOONFALL"] = "Maestra de vuelo: Kelya Moonfall"
L["BTWQUESTS_GIFT_OF_NZOTH"] = "Don de N'Zoth"
L["BTWQUESTS_GIFT_OF_NZOTH_BREADCRUMB"] = "Matar a los naga en la misión mundial ¡Ataque de los naga!"
L["BTWQUESTS_HATI_REBORN"] = "Hati renacido"
L["BTWQUESTS_HERITAGE_OF_GILNEAS"] = "Legado de Gilneas"
L["BTWQUESTS_HERITAGE_OF_GNOMEREGAN"] = "Legado de Gnomeregan"
L["BTWQUESTS_HERITAGE_OF_KEZAN"] = "Legado de Kezan"
L["BTWQUESTS_HERITAGE_OF_THE_BRONZEBEARD"] = "Legado de los Barbabronce"
L["BTWQUESTS_HERITAGE_OF_THE_SHUHALO"] = "Legado de los Shu'halo"
L["BTWQUESTS_HERITAGE_OF_THE_SINDOREI"] = "Legado de los Sin'dorei"
L["BTWQUESTS_ITEM_POCKET_SIZED_COMPUTATION_DEVICE"] = "Item: Dispositivo de cálculo de bolsillo"
L["BTWQUESTS_MAGHAR_ORC"] = "Orco Mag'har"
L["BTWQUESTS_MAJO_AND_JOMA"] = "Majo y Joma"
L["BTWQUESTS_NIGHT_WARRIOR_NIGHT_ELF_CUSTOMIZATION"] = "Personalización para elfo de la noche de \"guerrero nocturno\""
L["BTWQUESTS_PROGRESS_THE_WAR_CAMPAIGN"] = "Progresar en la campaña de guerra"
L["BTWQUESTS_THE_WAR_CAMPAIGN"] = "La campaña de guerra"
L["BTWQUESTS_THE_WAR_CAMPAIGN_8_1"] = "La campaña de guerra: Batalla de Dazar'alor"
L["BTWQUESTS_THE_WAR_CAMPAIGN_8_1_5"] = "La campaña de guerra: Crisol de Tormentas"
L["BTWQUESTS_THE_WAR_CAMPAIGN_8_2"] = "La campaña de guerra: Ascenso de Azshara"
L["BTWQUESTS_UNLOCK_FLIGHT_WHISTLE"] = "Desbloquear silbato de vuelo"
L["BTWQUESTS_VENDOR_MRRL"] = "Vendedor: Mrrl"
L["BTWQUESTS_WARFRONT_THE_BATTLE_FOR_DARKSHORE"] = "Frente de batalla: La Batalla por Costa Oscura"
L["COLLECT_AN_ASHVANE_DISGUISE"] = "Recoger un disfraz de Ashvane"
L["DUNGEON_KINGS_REST"] = "Calabozo: Reposo de los Reyes"
L["DUNGEON_SIEGE_OF_BORALUS"] = "Calabozo: Asedio de Boralus"
L["MECHAGNOME"] = "Mecagnomo"
L["PET_BUMBLES_OR_SEABREEZE_BUMBLEBEE"] = "Mascota: Bumbles o Seabreeze Bumblebee"
L["PICK_A_LOA"] = "Elegir un loa"
L["RAISE_YOUR_DIREHORN_TO_A_JUVENILE"] = "Elevar tu Direhorn a un Juvenil"
L["RAISE_YOUR_DIREHORN_TO_MATURITY"] = "Elevar tu Direhorn a la Madurez"
L["RISE_OF_AZSHARA_ZONES"] = "Zonas del Ascenso de Azshara"
L["SUMMON_BUMBLES_OR_SEABREEZE_BUMBLEBEE"] = "Invocar a Bumbles o Seabreeze Bumblebee"
L["VISIONS_OF_NZOTH"] = "Visiones de N'Zoth"
L["VULPERA"] = "Vulpera"
L["WAIST_OF_TIME"] = "Pérdida de tiempo"
L["WAIT_UNTIL_AVAILABLE"] = "Esperar hasta que esté disponible"
